language: r
r:
  - release
  - devel
cache: packages
sudo: false

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
r_binary_packages:
 - RcppRoll
 - dplyr
 - dbscan
 - knitr
 - ggplot2

r_github_packages:
  - Zelazny7/isofor
