---
title: "Outlier Detection"
author: "Michael Koohafkan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Outlier Detection}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This document compares outlier detection methods against a sample 
dataset.

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE
)
```

```{r}
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(ODWGtools)
```

```{r}
# get data
data("bdl")

# add some groupings
bdl = bdl %>%
  mutate(
    MONTH = format(DATETIME, "%b"),
    YEAR = format(DATETIME, "%Y"),
    DAYMON = format(DATETIME, "%b-%d")
  )
```

# ungrouped outlier detection

```{r}
bdl.none = bdl %>%
  mutate(
    tukey = tukey_outliers(VALUE, QAQC_FLAG == "G"),
    zscore = zscore_outliers(VALUE, QAQC_FLAG == "G"),
    tscore = tscore_outliers(VALUE, QAQC_FLAG == "G"),
    chisq = chisq_outliers(VALUE, QAQC_FLAG == "G"),
    mad = mad_outliers(VALUE, QAQC_FLAG == "G"),
#    isofor = isofor_outliers(VALUE, QAQC_FLAG == "G"),
#    lof = lof_outliers(VALUE, QAQC_FLAG == "G")
  ) %>%
  ungroup() %>%
  select(-MONTH, - YEAR, - DAYMON) %>%
  mutate(
    extreme.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% "extreme outlier")
    ),
    mild.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% c("mild outlier", "extreme outlier"))
    ),
    not.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% c("not outlier"))
    )
  )
```

# Year grouping

```{r}
# group by year
bdl.year = bdl %>%
  group_by(YEAR) %>%
  mutate(
    tukey = tukey_outliers(VALUE, QAQC_FLAG == "G"),
    zscore = zscore_outliers(VALUE, QAQC_FLAG == "G"),
    tscore = tscore_outliers(VALUE, QAQC_FLAG == "G"),
    chisq = chisq_outliers(VALUE, QAQC_FLAG == "G"),
    mad = mad_outliers(VALUE, QAQC_FLAG == "G"),
#    isofor = isofor_outliers(VALUE, QAQC_FLAG == "G"),
#    lof = lof_outliers(VALUE, QAQC_FLAG == "G")
  ) %>%
  ungroup() %>%
  select(-MONTH, - DAYMON) %>%
  mutate(
    extreme.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% "extreme outlier")
    ),
    mild.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% c("mild outlier", "extreme outlier"))
    ),
    not.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% c("not outlier"))
    )
  )
```

# Month grouping

```{r}
# group by month
bdl.mon = bdl %>%
  group_by(MONTH) %>%
  mutate(
    tukey = tukey_outliers(VALUE, QAQC_FLAG =="G"),
    zscore = zscore_outliers(VALUE, QAQC_FLAG == "G"),
    tscore = tscore_outliers(VALUE, QAQC_FLAG == "G"),
    chisq = chisq_outliers(VALUE, QAQC_FLAG == "G"),
    mad = mad_outliers(VALUE, QAQC_FLAG == "G"),
#    isofor = isofor_outliers(VALUE, QAQC_FLAG == "G"),
#    lof = lof_outliers(VALUE, QAQC_FLAG == "G")
  ) %>%
  ungroup() %>%
  select(- YEAR, - DAYMON) %>%
  mutate(
    extreme.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% "extreme outlier")
    ),
    mild.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% c("mild outlier", "extreme outlier"))
    ),
    not.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% c("not outlier"))
    )
  )
```

# Month-Day grouping

```{r}
bdl.daymon = bdl %>%
   group_by(DAYMON) %>%
  mutate(
    tukey = tukey_outliers(VALUE, QAQC_FLAG == "G"),
    zscore = zscore_outliers(VALUE, QAQC_FLAG == "G"),
    tscore = tscore_outliers(VALUE, QAQC_FLAG == "G"),
    chisq = chisq_outliers(VALUE, QAQC_FLAG == "G"),
    mad = mad_outliers(VALUE, QAQC_FLAG == "G"),
#    isofor = isofor_outliers(VALUE, QAQC_FLAG == "G"),
#    lof = lof_outliers(VALUE, QAQC_FLAG == "G")
  ) %>%
  ungroup() %>%
  select(-MONTH, - YEAR) %>%
  mutate(
    extreme.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% "extreme outlier")
    ),
    mild.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% c("mild outlier", "extreme outlier"))
    ),
    not.outlier.score = pmap(
      list(zscore, tscore, chisq, mad),
      function(...) sum(list(...) %in% c("not outlier"))
    )
  )
```

# Figures

## Good data only

```{r}
bdl.none %>%
   filter(QAQC_FLAG == "G") %>%
   select(-extreme.outlier.score, - mild.outlier.score, - not.outlier.score) %>%
   gather(test, tag, - DATETIME, - VALUE, - QAQC_FLAG) %>%
   ggplot() +
     aes(x = VALUE, fill = tag) +
     geom_density(alpha = 0.25) +
     facet_wrap(~test, scales = "free_y") +
     scale_fill_manual(NULL, values = c(
       "not outlier" = "cornflowerblue",
       "mild outlier" = "#ffeda0",
       "extreme outlier" = "#fc4e2a"))

bdl.year %>%
   filter(QAQC_FLAG == "G") %>%
   select(-extreme.outlier.score, - mild.outlier.score, - not.outlier.score) %>%
   gather(test, tag, - DATETIME, - YEAR, - VALUE, - QAQC_FLAG) %>%
   ggplot() +
     aes(x = VALUE, fill = tag) +
     geom_density(alpha = 0.25) +
     facet_grid(YEAR ~ test, scales = "free_y") +
     scale_fill_manual(NULL, values = c(
       "not outlier" = "cornflowerblue",
       "mild outlier" = "#ffeda0",
       "extreme outlier" = "#fc4e2a"))

bdl.mon %>%
   filter(QAQC_FLAG == "G") %>%
   select(-extreme.outlier.score, - mild.outlier.score, - not.outlier.score) %>%
   mutate(MONTH = factor(MONTH, month.abb)) %>%
   gather(test, tag, - DATETIME, - MONTH, - VALUE, - QAQC_FLAG) %>%
   ggplot() +
     aes(x = VALUE, fill = tag) +
     geom_density(alpha = 0.25) +
     facet_grid(MONTH ~ test, scales = "free_y") +
     scale_fill_manual(NULL, values = c(
       "not outlier" = "cornflowerblue",
       "mild outlier" = "#ffeda0",
       "extreme outlier" = "#fc4e2a"))
```

## Bad data only

```{r}
bdl.none %>%
   filter(QAQC_FLAG == "X") %>%
   select(-extreme.outlier.score, - mild.outlier.score, - not.outlier.score) %>%
   gather(test, tag, - DATETIME, - VALUE, - QAQC_FLAG) %>%
   ggplot() +
     aes(x = VALUE, fill = tag) +
     geom_density(alpha = 0.25) +
     facet_wrap(~test, scales = "free_y") +
     scale_fill_manual(NULL, values = c(
       "not outlier" = "cornflowerblue",
       "mild outlier" = "#ffeda0",
       "extreme outlier" = "#fc4e2a"))

bdl.year %>%
   filter(QAQC_FLAG == "X") %>%
   select(-extreme.outlier.score, - mild.outlier.score, - not.outlier.score) %>%
   gather(test, tag, - DATETIME, - YEAR, - VALUE, - QAQC_FLAG) %>%
   ggplot() +
     aes(x = VALUE, fill = tag) +
     geom_density(alpha = 0.25) +
     facet_grid(YEAR ~ test, scales = "free_y") +
     scale_fill_manual(NULL, values = c(
       "not outlier" = "cornflowerblue",
       "mild outlier" = "#ffeda0",
       "extreme outlier" = "#fc4e2a"))

bdl.mon %>%
   filter(QAQC_FLAG == "X") %>%
   select(-extreme.outlier.score, - mild.outlier.score, - not.outlier.score) %>%
   mutate(MONTH = factor(MONTH, month.abb)) %>%
   gather(test, tag, - DATETIME, - MONTH, - VALUE, - QAQC_FLAG) %>%
   ggplot() +
     aes(x = VALUE, fill = tag) +
     geom_density(alpha = 0.25) +
     facet_grid(MONTH ~ test, scales = "free_y") +
     scale_fill_manual(NULL, values = c(
       "not outlier" = "cornflowerblue",
       "mild outlier" = "#ffeda0",
       "extreme outlier" = "#fc4e2a"))
```
